spring:
  application:
    name: QuoraApp
  data:
    mongodb:
      host: localhost
      port: 27017
      database: Quora_db
      auto-index-creation: true

  elasticsearch:
    uris: http://localhost:9200